Added the blogs and Youtube links
kaiwalyakoparkar/practical-devops pull request #18
Opened 2023-03-23 15:50 UTC by mnik7044

Worked on the issue #10 I have added the youtube videos and blogs for the helm and prometheus file, also added the argocd blog and corrected the format in the rust file.

2023-03-30 11:40 UTC, mnik7044 commented
Hey @kaiwalyakoparkar  have you reviewed it?

2023-04-02 05:12 UTC, kaiwalyakoparkar commented
Hey @mnik7044 thank you so much for your patience, I will start reviewing it shortly

2023-04-06 13:46 UTC, kaiwalyakoparkar requested changes

2023-04-06 13:46 UTC, kaiwalyakoparkar commented on Helm/Readme.md
> +
Kindly remove such extra lines

2023-04-06 13:46 UTC, kaiwalyakoparkar commented on Helm/Readme.md
> +
Same. remove unnecessary lines here

2023-04-06 13:46 UTC, kaiwalyakoparkar commented on Prometheus/Readme.md
> +
Remove this extra lines

2023-04-12 23:33 UTC, mnik7044 commented
Hey @kaiwalyakoparkar  just wanted to know that whether I need to delete this pr and add a new pr or if I do the changes now it will be reflected in the current pr only?

2023-04-12 23:44 UTC, mnik7044 commented
Hey @kaiwalyakoparkar I have removed all the extra lines, please review it.

2023-04-13 05:32 UTC, kaiwalyakoparkar requested changes

2023-04-13 05:32 UTC, kaiwalyakoparkar commented on Prometheus/Readme.md
> +# Steps and commands
Please add one empty line before and after the heading please (for all the files)

2023-04-13 14:57 UTC, kaiwalyakoparkar approved these changes
lgtm, thank you so much for contributing

2023-04-13 15:00 UTC, merged

2023-04-13 15:01 UTC, mnik7044 commented
Thank you for this opportunity will be looking to contribute more in the coming days.